### ISSUE TITLE
Missing Getting Started with Johnny Five and JY MCU Bluetooth Serial Port Module

### ISSUE THREAD

**Issue by bmf** [bocoup/johnny-five.io#44]
I was unable to locate this article https://github.com/rwaldron/johnny-five/wiki/Getting-Started-with-Johnny-Five-and-JY-MCU-Bluetooth-Serial-Port-Module or anything talking about the JY-MCU module. Not sure if this was by design. If not, how can I help to get it up there?

Also - Great job to everyone contributing to this project. This is an excellent resource and it's much appreciated.

**Comment by rwaldron** [comment]
It's here: http://johnny-five.io/api/

Currently, those links go back to the repo, but I plan on doing a formal migration in very near future

**Comment by bmf** [comment]
That works for me! Thank you for your help.

**Comment by rwaldron** [comment]
Awesome :)
