### ISSUE TITLE
Set og:* properties for Facebook sharing

### ISSUE THREAD

**Issue by Resseguie** [bocoup/johnny-five.io#45]
The default shared image for Facebook is one of the specific boards. We should add meta properties to point to a more reasonable (logo? Johnny-Five drawing?) suggestion.

Here is Facebook's debugger output for the website:
https://developers.facebook.com/tools/debug/og/object?q=http%3A%2F%2Fjohnny-five.io

Not explicitly listed at that link, the preview image must be a minimum of 200x200.

**Comment by rwaldron** [comment]
Go for it!

**Comment by Resseguie** [comment]
Also, we could pass in a suggested image specific to each example from the J5 programs.json file for the generated example pages.

**Comment by pierceray** [comment]
Preferably they want a 1.91:1 ratio image.  Suggested size is 1200x630.

https://developers.facebook.com/docs/sharing/best-practices#images

There doesn't appear to be anything in the repo already that would be appropriate to use for the `og:image` property.  Is there a graphic designer that could create one for us as the default?

**Comment by rwaldron** [comment]
@isaacdurazo ^^

**Comment by Resseguie** [comment]
@pierceray looks good to me, based on my limited understanding of the FB usage. 

Is there a way to run the result through that FB debugger link before publishing it? I don't see an option for that. Maybe we could stage it somewhere and test against that before deploying?

The image is the main thing I was looking for here, so I suggest we wait for an appropriate logo, add a commit for that, then push it out. 

@rwaldron do you just want the Johnny-Five logo for all pages? Or something different for the other page types: examples, API, etc?

**Comment by rwaldron** [comment]
@Resseguie not sure, that's why I pinged @isaacdurazo (he's the lead designer @bocoup)

**Comment by pierceray** [comment]
I haven't found a way to easily stage it somewhere to run it through the debugger.  I'll if I can't find somewhere to do it tonight.

Yes, I would agree about the image, I just didn't have one available to me to add that would be appropriate.

**Comment by isaacdurazo** [comment]
Hey guys, would something like this work?
![j5-facebook-sharing](https://cloud.githubusercontent.com/assets/1379244/7990798/37bdddfc-0aa8-11e5-8f04-56c321f893bc.png)

**Comment by pierceray** [comment]
I think that will work great.  I'll get it integrated tonight.

**Comment by isaacdurazo** [comment]
@Resseguie I Iike the idea of having something different for each section (as long as it's not a ton of work to implement them), specially because the "Examples" page has a board and it's pretty damn cool.

I would say, let's use the one I just posted as the default and give me some time to work on the rest. I should have time early next week (maybe before).

**Comment by pierceray** [comment]
Should we spin up a new issue for section images and just set everything to default for the time being?

**Comment by Resseguie** [comment]
@pierceray sounds good to me. This issue would put in the needed meta tags with default. (As your PR does)

**Comment by pierceray** [comment]
Looks like it is good to go now.  Added the `og:image` and new image file.  Tested it on a temp site and the FB Object Debugger worked as expected.
