### ISSUE TITLE
Capitalization in URL breaks links on LED API page

### ISSUE THREAD

**Issue by davidrleonard** [bocoup/johnny-five.io#49]
This is the page: http://johnny-five.io/api/led/

The links under `See Also` all lead to 404.

For example, this link is bad: http://johnny-five.io/api/Led.Digits

A lowercase version of the link is good: http://johnny-five.io/api/led.digits

**Comment by rwaldron** [comment]
nice catch!

**Comment by pierceray** [comment]
Is this just a matter of updating the wiki docs to use lowercase pathing?  I've found a couple other pages that have the same issue.

Could some rewrite rules be written to handle this if it occurs in the future?

**Comment by pierceray** [comment]
Updated 
https://github.com/rwaldron/johnny-five/wiki/led
https://github.com/rwaldron/johnny-five/wiki/ping
https://github.com/rwaldron/johnny-five/wiki/sonar

**Comment by rwaldron** [comment]
Where were those linked from?

**Comment by pierceray** [comment]
Those were the pages with the bad links.
* [led diff](https://github.com/rwaldron/johnny-five/wiki/Led/_compare/937315ac151c5d1f467647565d2c5a15d3942c25...c51552002635999ae75aa3cfddd5a995794fa6c9)
* [ping diff](https://github.com/rwaldron/johnny-five/wiki/Ping/_compare/6e3c035df620248eccde9bb9361e45297aaf8514...d37cc10131940fe92dfc5ddd23b40236d67bde44)
* [sonar diff](https://github.com/rwaldron/johnny-five/wiki/Sonar/_compare/fae71477df650d1b2e1e4a7286f7736c93d88f95...196af1787178568cff93ceaa9a281765c888993a)

**Comment by rwaldron** [comment]
Oh, got it—thanks :)

**Comment by pierceray** [comment]
I missed an instance of the capitalized Animation in /api/led.  I corrected it now, so next deploy should pick it up.

**Comment by rwaldron** [comment]
Thanks again @pierceray —I'm running deploy right now :)

**Comment by pierceray** [comment]
I think this can be closed, unless you are going to automate it in some way.

**Comment by rwaldron** [comment]
I hadn't thought about it—I'm going to close for now. Thanks again for helping out with this :)

**Comment by frxnz** [comment]
I don't know what environment this site runs in, but enforcing lowercase URLs with a 301 rewrite rule in the server config is pretty standard practice. That would prevent issues like this from popping up in the future.

**Comment by rwaldron** [comment]
@tkellen might know something about that
