### ISSUE TITLE
apilist is including bad links in the "Component Classes in this example"

### ISSUE THREAD

**Issue by pierceray** [bocoup/johnny-five.io#59]
There are quite a few examples that are having a bad links inserted into the "Component Classes in this example" section.  There is an assumption that the classes will have an equivalent /api/<class> page on the site, but that is not the case. Repl, LedControl, Fn, IR, Distance.

Examples:
http://johnny-five.io/examples/servo-animation/ - Repl (lots of other examples)
http://johnny-five.io/examples/led-matrix-tutorial/ - LedControl
http://johnny-five.io/examples/servo-array/ - Fn (lots of other examples)
http://johnny-five.io/examples/ir-proximity/ -IR (lots of other examples)
http://johnny-five.io/examples/sonar/ - Distance

This is coming from the Gruntfile.js
```
var apilist = apinames.filter(function(apiname) {
  if (contents.includes(apiname)) {
    return true;
  }
}).map(function(apiname) {
  return "- [" + apiname + "](/api/" + apiname.toLowerCase() + ")";
}).join("\n");
```

Not sure what the desired output should be, but a link that 404's is probably not desired.

**Comment by pierceray** [comment]
Found a few more.

http://johnny-five.io/examples/classic-controller/ - Wii
http://johnny-five.io/examples/navigator/ - Gripper
http://johnny-five.io/examples/nodebot/ - Nodebot

**Comment by rwaldron** [comment]
I can fix this now

**Comment by rwaldron** [comment]
Also, thanks for reviewing all of this content!
