### ISSUE TITLE
Link to pinoccio scout runtime wrong?

### ISSUE THREAD

**Issue by beriberikix** [bocoup/johnny-five.io#60]
https://github.com/bocoup/johnny-five.io/blob/5a89d435ef02c7a13f71442f7d12e71dd850c3ac/src/platforms-plugins.json#L834

Guessing that should be https://pinocc.io/?

**Comment by rwaldron** [comment]
Whoops! Yes. Thank you :D

**Comment by beriberikix** [comment]
:+1:
